from os.path import join

import numpy as np
import pandas as pd

from tests.files.paths import generator_sol_path, files_path

gen_missing_band_sol_path = join(generator_sol_path, 'generator_missing_band_solution.csv')
no_correction_solution_path = join(generator_sol_path, 'generator_solution_with_missing_BP.csv')
correction_solution_path = join(generator_sol_path, 'generator_solution_with_missing_BP_error_correction.csv')

# Photometric systems specifications to compare with objects generated by the package 'converters' is used to parse
# bands and zero_points.
phot_systems_specs = pd.read_csv(join(files_path, 'PhotometricSystemSpecs.csv'),
                                 converters={'bands': lambda x: x[1:-1].split(','),
                                             'zero_points': lambda y: np.array(y[1:-1].split(',')).astype(float)},
                                 float_precision='high')