from os.path import abspath, dirname, join

files_path = abspath(join(dirname(__file__)))

output_path = 'tests_output_files'  # Store output files generated by the tests in this folder
solution_path = join(files_path, 'output_solution')  # Read the expected solution to compare with the output files

# Load XP continuous file
continuous_path = join(files_path, 'xp_continuous')
# Regular mean spectra files
mean_spectrum_avro_file = join(continuous_path, 'MeanSpectrumSolutionWithCov.avro')
mean_spectrum_csv_file = join(continuous_path, 'XP_CONTINUOUS_RAW.csv')
mean_spectrum_ecsv_file = join(continuous_path, 'XP_CONTINUOUS_RAW.ecsv')
mean_spectrum_fits_file = join(continuous_path, 'XP_CONTINUOUS_RAW.fits')
mean_spectrum_xml_file = join(continuous_path, 'XP_CONTINUOUS_RAW.xml')
mean_spectrum_xml_plain_file = join(continuous_path, 'XP_CONTINUOUS_RAW_plain.xml')
# Three sources including the one without BP
with_missing_bp_csv_file = join(continuous_path, 'XP_CONTINUOUS_RAW_with_missing_BP.csv')
with_missing_bp_ecsv_file = join(continuous_path, 'XP_CONTINUOUS_RAW_with_missing_BP.ecsv')
with_missing_bp_fits_file = join(continuous_path, 'XP_CONTINUOUS_RAW_with_missing_BP.fits')
with_missing_bp_xml_file = join(continuous_path, 'XP_CONTINUOUS_RAW_with_missing_BP.xml')
with_missing_bp_xml_plain_file = join(continuous_path, 'XP_CONTINUOUS_RAW_with_missing_BP_plain.xml')
# The missing BP source isolated
missing_bp_csv_file = join(continuous_path, 'XP_CONTINUOUS_RAW_missing_BP_dr3int6.csv')
missing_bp_ecsv_file = join(continuous_path, 'XP_CONTINUOUS_RAW_missing_BP_dr3int6.ecsv')
missing_bp_fits_file = join(continuous_path, 'XP_CONTINUOUS_RAW_missing_BP_dr3int6.fits')
missing_bp_xml_file = join(continuous_path, 'XP_CONTINUOUS_RAW_missing_BP_dr3int6.xml')
missing_bp_xml_plain_file = join(continuous_path, 'XP_CONTINUOUS_RAW_missing_BP_plain_dr3int6.xml')
